### ISSUE TITLE
raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Deanagage** [fulfilio/pyepc#2]
* Python MWS Client version: 
* Python version: 3.7
* Operating System: Windows

### Description

Simple entry using 'GTIN to EPC' convert
Throws a Jsondecode error in the terminal output, expected outcome was converted GTIN.

### What I Did

```
from pyepc import SGTIN

company_prefix_len = len('0614141')                 #Also tried without this line to establish len
SGTIN.from_sgtin('80614141123458', '6789AB')

```
Output:
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sharoonthomas** [comment]
When the length of the company prefix is not provided, a json file is loaded from GS1.org

https://github.com/fulfilio/pyepc/blob/7fe63ffbf5023be5719a39dfaee7cd214ed2f800/pyepc/utils.py#L170-L175

```
from pyepc import SGTIN
SGTIN.from_sgtin('80614141123458', '6789AB', len('0614141'))
```
Should get you the sgtin without hitting the company prefix db
